import Head from "next/head";
import style from "./title.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={style.tit}>Master</h1>
        <h1 className={style.tit}>hello1</h1>
      </main>
    </>
  );
}
